# To enable the "Sponsor" button at the top of this repo, fill in the
# relevant fields below. See
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# github:    AnarchySC            # <-- your GitHub Sponsors username (when enrolled)
# patreon:   <username>
# ko_fi:     <username>
# liberapay: <username>
custom: ['https://anarchygames.org']
